
trigger:
# if push was before the pipline finished then wait 
  batch: true  
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - azure-pipelines.yml


pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  
- powershell:   $(System.DefaultWorkingDirectory)\build.ps1
  displayName:  Build via Cake
  
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)\syntax\bin\Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\syntax'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)\money\bin\Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\money'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'D:\a\1\s\ExpectedExceptionExample\bin\Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\ExpectedExceptionExample'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: 'TestResult.xml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: NUnit
    testResultsFiles: '$(System.DefaultWorkingDirectory)/TestResult.xml'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'artifacts'
    publishLocation: 'Container'

