
trigger:
# if push was before the pipline finished then wait 
  batch: true  
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - azure-pipelines.yml


variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:

- job: build_project
  displayName: Build all artifacts
  pool:
    vmImage: 'windows-latest'
  timeoutInMinutes: 90
  steps:
  - template: ci/build.yml
    parameters:
      solution: Windows_NT
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

