
trigger:
# if push was before the pipline finished then wait 
  batch: true  
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - azure-pipelines.yml


pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- powershell:  Get-ChildItem $(System.DefaultWorkingDirectory)
  displayName:  Powershell list
  
- powershell:   $(System.DefaultWorkingDirectory)\build.ps1
  displayName:  Build
  
  
- task: CopyFiles@2
  inputs:
    SourceFolder: 'D:\a\1\s\syntax\bin\Release'
    Contents: '**'
    TargetFolder: 'D:\a\1\a\syntax'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'D:\a\1\s\money\bin\Release'
    Contents: '**'
    TargetFolder: 'D:\a\1\a\money'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'D:\a\1\s\ExpectedExceptionExample\bin\Release'
    Contents: '**'
    TargetFolder: 'D:\a\1\a\ExpectedExceptionExample'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'D:\a\1\s\DataDrivenTests\bin\Release'
    Contents: '**'
    TargetFolder: 'D:\a\1\a\DataDrivenTests'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'artifacts'
    publishLocation: 'Container'

